#!/bin/bash

# pluginname=$(basename $0 .sh)
pluginname=REPLACELBPPLUGINDIR
touch $LBPLOG/$pluginname/wu4lox.log > /dev/null 2>&1

echo "DAEMON: Starting DAEMON script" >> $LBPLOG/$pluginname/wu4lox.log
if [ -x /usr/bin/logger ]; then
    /usr/bin/logger "loxberry-plugin-$pluginname - DAEMON Script from WU4Lox Plugin"
fi

# Creating logfiles and databases in RAM disk
echo "DAEMON: Creating databases and logfiles in RAM Disk" >> $LBPLOG/$pluginname/wu4lox.log
if [ -x /usr/bin/logger ]; then
    /usr/bin/logger "loxberry-plugin-$pluginname - Creating databases and logfiles in RAM Disk"
fi
touch $LBPLOG/$pluginname/current.dat
touch $LBPLOG/$pluginname/hourlyforecast.dat
touch $LBPLOG/$pluginname/dailyforecast.dat
chown -vR loxberry:loxberry $LBPLOG/$pluginname/* 

exit 0
