#!/bin/bash

# pluginname=$(basename $0 .sh)
pluginname=REPLACELBPPLUGINDIR
touch $LBPLOG/$pluginname/wu4lox.log > /dev/null 2>&1

echo "DAEMON: Starting DAEMON script" >> $LBPLOG/$pluginname/wu4lox.log
if [ -x /usr/bin/logger ]; then
    /usr/bin/logger "loxberry-plugin-$pluginname - DAEMON Script from WU4Lox Plugin"
fi

# Creating logfiles and databases in RAM disk
echo "DAEMON: Restoring databases and logfiles in RAM Disk" >> $LBPLOG/$pluginname/wu4lox.log
if [ -x /usr/bin/logger ]; then
    /usr/bin/logger "loxberry-plugin-$pluginname - Restoring databases and logfiles in RAM Disk"
fi

echo "DAEMON: Restore databases" >> $LBPLOG/$pluginname/wu4lox.log
if [ ! -e $LBPLOG/$pluginname/current.dat ]; then
	cp $LBPDATA/$pluginname/current.dat $LBPLOG/$pluginname/
fi
if [ ! -e $LBPLOG/REPLACELBPPLUGINDIR/dailyforecast.dat ]; then
	cp $LBPDATA/$pluginname/dailyforecast.dat $LBPLOG/$pluginname/
fi
if [ ! -e $LBPLOG/opt/loxberry/log/plugins/REPLACELBPPLUGINDIR/hourlyforecast.dat ]; then
	cp $LBPDATA/$pluginname/hourlyforecast.dat $LBPLOG/$pluginname/
fi
if [ ! -e $LBPLOG/opt/loxberry/log/plugins/REPLACELBPPLUGINDIR/hourlyhistory.dat ]; then
	cp $LBPDATA/$pluginname/hourlyhistory.dat $LBPLOG/$pluginname/
fi
if [ ! -e $LBPLOG/opt/loxberry/log/plugins/REPLACELBPPLUGINDIR/webpage.html ]; then
	cp $LBPDATA/$pluginname/webpage.html $LBPLOG/$pluginname/
fi
if [ ! -e $LBPLOG/opt/loxberry/log/plugins/REPLACELBPPLUGINDIR/webpage.map.html ]; then
	cp $LBPDATA/$pluginname/webpage.map.html $LBPLOG/$pluginname/
fi
if [ ! -e $LBPLOG/opt/loxberry/log/plugins/REPLACELBPPLUGINDIR/webpage.dfc.html ]; then
	cp $LBPDATA/$pluginname/webpage.dfc.html $LBPLOG/$pluginname/
fi
if [ ! -e $LBPLOG/opt/loxberry/log/plugins/REPLACELBPPLUGINDIR/webpage.hfc.html ]; then
	cp $LBPDATA/$pluginname/webpage.hfc.html $LBPLOG/$pluginname/
fi
if [ ! -e $LBPLOG/opt/loxberry/log/plugins/REPLACELBPPLUGINDIR/weatherdata.html ]; then
	cp $LBPDATA/$pluginname/weatherdata.html $LBPLOG/$pluginname/
fi
if [ ! -e $LBPLOG/opt/loxberry/log/plugins/REPLACELBPPLUGINDIR/index.txt ]; then
	cp $LBPDATA/$pluginname/index.txt $LBPLOG/$pluginname/
fi
chown -vR loxberry:loxberry $LBPLOG/$pluginname/* 

# Exit with Status 0
exit 0
